import pprint

data = {'created_at': '2021-12-15T01:14:28Z',
 'description': 'Measured temperature by the Si7021 sensor connected to '
                'Adafruit Feather Huzzah32.',
 'details': {'dashboards': [{'key': 'temperature-humidity-history',
                             'name': 'Temperature and Humidity History',
                             'username': 'FlynntKnapp'}],
             'data': {'count': 39772,
                      'first': {'created_at': '2022-01-06T09:29:09Z',
                                'ele': '0.0',
                                'expiration': '1644053349.0',
                                'feed_id': 1767913,
                                'id': '0EXQ9K9KQJS5R8FKMY2ATGPK12',
                                'lat': '0.0',
                                'location': {'ele': '0.0',
                                             'lat': '0.0',
                                             'lon': '0.0'},
                                'lon': '0.0',
                                'updated_at': '2022-01-06T09:29:09Z',
                                'value': '65.20'},
                      'last': {'created_at': '2022-02-06T00:27:38Z',
                               'ele': '0.0',
                               'expiration': '1646699258.0',
                               'feed_id': 1767913,
                               'id': '0EYFY4N0GQB5VCXR869VXF29Z6',
                               'lat': '0.0',
                               'location': {'ele': '0.0',
                                            'lat': '0.0',
                                            'lon': '0.0'},
                               'lon': '0.0',
                               'updated_at': '2022-02-06T00:27:38Z',
                               'value': '66.94'}},
             'last_numeric_value_at': '2022-02-06T00:27:38Z',
             'last_value_at': '2022-02-06T00:27:38Z',
             'triggers': []},
 'enabled': True,
 'feed_status_changes': [],
 'feed_webhook_receivers': [],
 'group': {'id': 55706,
           'key': 'feather-iot',
           'name': 'FeatherIOT',
           'user_id': 63146},
 'groups': [{'id': 55706,
             'key': 'feather-iot',
             'name': 'FeatherIOT',
             'user_id': 63146}],
 'history': True,
 'id': 1767913,
 'key': 'temperatureesp32',
 'last_value': '66.94',
 'license': None,
 'name': 'Temperature ESP32',
 'owner': {'id': 63146, 'username': 'FlynntKnapp'},
 'status': 'online',
 'status_notify': False,
 'status_timeout': 4320,
 'unit_symbol': None,
 'unit_type': None,
 'updated_at': '2022-02-06T00:27:38Z',
 'username': 'FlynntKnapp',
 'visibility': 'public',
 'wipper_pin_info': None,
 'writable': True}

# pprint.pprint(data)

pprint.pprint(data['details']['data']['last'])
