
# https://io.adafruit.com/api/v2/{username}/feeds


import pprint

headers = {'server': 'nginx', 'date': 'Sun, 06 Feb 2022 00:40:21 GMT', 'content-type': 'application/json; charset=utf-8', 'transfer-encoding': 'chunked', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'x-download-options': 'noopen', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'strict-origin-when-cross-origin', 'x-aio-worker': 'io-rails-1', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'false', 'access-control-request-method': '*', 'access-control-allow-methods': 'POST, PUT, DELETE, GET, OPTIONS, PATCH', 'access-control-allow-headers': 'DNT, Origin, X-Requested-With, X-AIO-Key, Content-Type, Accept, Authorization', 'access-control-expose-headers': 'X-Pagination-Limit, X-Pagination-Start, X-Pagination-End, X-Pagination-Count, X-Pagination-Total', 'access-control-max-age': '1728000', 'etag': 'W/"21ad7437c7e5f152b1505df7da75930d"', 'cache-control': 'max-age=0, private, must-revalidate', 'x-request-id': '37cbb80b-8925-4f66-89cd-df1bf01b2e62', 'x-runtime': '0.068097', 'content-encoding': 'gzip', 'x-aio-proxy': '1', 'strict-transport-security': 'max-age=31536000', 'permissions-policy': 'interest-cohort=()'}


data = [{'created_at': '2020-02-17T15:07:15Z',
  'description': 'Measured temperature by the Si7021. Sensor is connected to '
                 'Adafruit Feather HUZZAH ESP8266.',
  'enabled': True,
  'feed_status_changes': [{'created_at': '2021-12-15T01:01:15Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'offline',
                           'to_status': 'online'},
                          {'created_at': '2021-11-15T13:40:10Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'online',
                           'to_status': 'offline'},
                          {'created_at': '2020-07-11T18:27:23Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'offline',
                           'to_status': 'online'},
                          {'created_at': '2020-07-09T20:40:11Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'online',
                           'to_status': 'offline'}],
  'feed_webhook_receivers': [],
  'group': {'id': 55706,
            'key': 'feather-iot',
            'name': 'FeatherIOT',
            'user_id': 63146},
  'groups': [{'id': 55706,
              'key': 'feather-iot',
              'name': 'FeatherIOT',
              'user_id': 63146}],
  'history': True,
  'id': 1303967,
  'key': 'temperatureesp8266',
  'last_value': '69.47',
  'license': None,
  'name': 'Temperature ESP8266',
  'owner': {'id': 63146, 'username': 'FlynntKnapp'},
  'status': 'online',
  'status_notify': False,
  'status_timeout': 4320,
  'unit_symbol': None,
  'unit_type': None,
  'updated_at': '2022-02-06T00:39:26Z',
  'username': 'FlynntKnapp',
  'visibility': 'public',
  'wipper_pin_info': None},
 {'created_at': '2020-02-17T22:04:12Z',
  'description': 'Measured humidity by the Si7021. Sensor is connected to '
                 'Adafruit Feather HUZZAH ESP8266.',
  'enabled': True,
  'feed_status_changes': [{'created_at': '2021-12-15T01:01:16Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'offline',
                           'to_status': 'online'},
                          {'created_at': '2021-11-15T13:40:10Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'online',
                           'to_status': 'offline'},
                          {'created_at': '2020-07-11T18:27:23Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'offline',
                           'to_status': 'online'},
                          {'created_at': '2020-07-09T20:40:11Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'online',
                           'to_status': 'offline'}],
  'feed_webhook_receivers': [],
  'group': {'id': 55706,
            'key': 'feather-iot',
            'name': 'FeatherIOT',
            'user_id': 63146},
  'groups': [{'id': 55706,
              'key': 'feather-iot',
              'name': 'FeatherIOT',
              'user_id': 63146}],
  'history': True,
  'id': 1304178,
  'key': 'humidityesp8266',
  'last_value': '31.4',
  'license': None,
  'name': 'Humidity ESP8266',
  'owner': {'id': 63146, 'username': 'FlynntKnapp'},
  'status': 'online',
  'status_notify': False,
  'status_timeout': 4320,
  'unit_symbol': None,
  'unit_type': None,
  'updated_at': '2022-02-06T00:39:26Z',
  'username': 'FlynntKnapp',
  'visibility': 'public',
  'wipper_pin_info': None},
 {'created_at': '2021-12-15T01:11:12Z',
  'description': 'Measured humidity by the Si7021 sensor connected to Adafruit '
                 'Feather Huzzah 32.',
  'enabled': True,
  'feed_status_changes': [],
  'feed_webhook_receivers': [],
  'group': {'id': 55706,
            'key': 'feather-iot',
            'name': 'FeatherIOT',
            'user_id': 63146},
  'groups': [{'id': 55706,
              'key': 'feather-iot',
              'name': 'FeatherIOT',
              'user_id': 63146}],
  'history': True,
  'id': 1767912,
  'key': 'humidityesp32',
  'last_value': '33.0',
  'license': None,
  'name': 'Humidity ESP32',
  'owner': {'id': 63146, 'username': 'FlynntKnapp'},
  'status': 'online',
  'status_notify': False,
  'status_timeout': 4320,
  'unit_symbol': None,
  'unit_type': None,
  'updated_at': '2022-02-06T00:39:52Z',
  'username': 'FlynntKnapp',
  'visibility': 'public',
  'wipper_pin_info': None},
 {'created_at': '2021-12-15T01:14:28Z',
  'description': 'Measured temperature by the Si7021 sensor connected to '
                 'Adafruit Feather Huzzah32.',
  'enabled': True,
  'feed_status_changes': [],
  'feed_webhook_receivers': [],
  'group': {'id': 55706,
            'key': 'feather-iot',
            'name': 'FeatherIOT',
            'user_id': 63146},
  'groups': [{'id': 55706,
              'key': 'feather-iot',
              'name': 'FeatherIOT',
              'user_id': 63146}],
  'history': True,
  'id': 1767913,
  'key': 'temperatureesp32',
  'last_value': '66.86',
  'license': None,
  'name': 'Temperature ESP32',
  'owner': {'id': 63146, 'username': 'FlynntKnapp'},
  'status': 'online',
  'status_notify': False,
  'status_timeout': 4320,
  'unit_symbol': None,
  'unit_type': None,
  'updated_at': '2022-02-06T00:39:49Z',
  'username': 'FlynntKnapp',
  'visibility': 'public',
  'wipper_pin_info': None},
 {'created_at': '2021-12-15T01:16:13Z',
  'description': 'Measured battery voltage of battery connected to Adafruit '
                 'Feather Huzzah32.',
  'enabled': True,
  'feed_status_changes': [],
  'feed_webhook_receivers': [],
  'group': {'id': 55706,
            'key': 'feather-iot',
            'name': 'FeatherIOT',
            'user_id': 63146},
  'groups': [{'id': 55706,
              'key': 'feather-iot',
              'name': 'FeatherIOT',
              'user_id': 63146}],
  'history': True,
  'id': 1767914,
  'key': 'batteryvoltageesp32',
  'last_value': '4.69',
  'license': None,
  'name': 'Battery Voltage of ESP32',
  'owner': {'id': 63146, 'username': 'FlynntKnapp'},
  'status': 'online',
  'status_notify': False,
  'status_timeout': 4320,
  'unit_symbol': None,
  'unit_type': None,
  'updated_at': '2022-02-06T00:39:55Z',
  'username': 'FlynntKnapp',
  'visibility': 'public',
  'wipper_pin_info': None},
 {'created_at': '2021-12-16T22:46:17Z',
  'description': 'Feed for toggling the LED.',
  'enabled': True,
  'feed_status_changes': [{'created_at': '2021-12-27T09:40:10Z',
                           'email_sent': None,
                           'email_sent_to': None,
                           'from_status': 'online',
                           'to_status': 'offline'}],
  'feed_webhook_receivers': [],
  'group': {'id': 55706,
            'key': 'feather-iot',
            'name': 'FeatherIOT',
            'user_id': 63146},
  'groups': [{'id': 55706,
              'key': 'feather-iot',
              'name': 'FeatherIOT',
              'user_id': 63146}],
  'history': True,
  'id': 1769478,
  'key': 'toggle-led',
  'last_value': 'ON',
  'license': None,
  'name': 'Toggle LED',
  'owner': {'id': 63146, 'username': 'FlynntKnapp'},
  'status': 'offline',
  'status_notify': False,
  'status_timeout': 4320,
  'unit_symbol': None,
  'unit_type': None,
  'updated_at': '2021-12-27T09:40:10Z',
  'username': 'FlynntKnapp',
  'visibility': 'public',
  'wipper_pin_info': None}]

# pprint.pprint(data)
# print(len(data))
# pprint.pprint(data[0])
# pprint.pprint(data[0]['created_at'])

for data_point in data:
  print(data_point['updated_at'])
  print(data_point['description'])
  print(data_point['id'])
  print(data_point['last_value'])